mixed_c_cpp:simple_compress.o test_c_simple_compress.o
	gcc -lstdc++ $^ -o $@

simple_compress.o: simple_compress.h simple_compress.cpp
	g++ -Wall -c -std=c++0x $^

c.o: simple_compress.h test_c_simple_compress.c
	gcc -Wall -c $^

.PHONY : clean
clean:
	-rm *.o mixed_c_cpp
